name: 'ghaction-BlazorWebAssemblyFileHashFixer'
description: 'GitHub Action to fix the sha256 file-hashes from the resources defined in "blazor.boot.json" and "service-worker-assets.js".'
author: 'sheyenrath'
branding:
  icon: 'hash'  
  color: 'purple'
inputs:
  wwwroot-path:
    description: 'wwwroot path'
    required: true
    default: '.'
runs:
  using: 'docker'
  image: 'docker://sheyenrath/blazor-webassembly-filehash-fixer:2'
  args:
    - ${{ inputs.wwwroot-path }}
