FROM mcr.microsoft.com/dotnet/core/runtime:3.1-bionic

LABEL maintainer="Stef Heyenrath"

# Copies your code file from your action repository to the filesystem path `/` of the container
COPY ./out/fixer fixer

RUN chmod +x ./fixer

# Code file to execute when the docker container starts up (`entrypoint.sh`)
ENTRYPOINT ["/fixer"]